/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import com.fasterxml.jackson.databind.ObjectMapper;
import com.github.fge.jsonpatch.JsonPatchException;
import org.junit.Assert;
import org.junit.Test;

import java.io.IOException;

import static org.junit.Assert.*;

public class AppTest {

    ObjectMapper mapper = new ObjectMapper();
    App classUnderTest = new App();

    @Test public void testReplaceCount() throws IOException, JsonPatchException {

        String jsonPatch = "[ { \"op\": \"replace\", \"path\": \"/count\", \"value\": 42 } ]";
        Thing thing = new Thing();
        String actualThingJson = classUnderTest.getPatched(jsonPatch, thing);

        Thing expectedThing = new Thing();
        expectedThing.setCount(42);
        String expectedThingJson = mapper.writeValueAsString(expectedThing);

        Assert.assertEquals("Thing count should be 42", expectedThingJson, actualThingJson);

    }

    @Test public void testReplaceNames() throws IOException, JsonPatchException {

        String jsonPatch = "[ { \"op\": \"replace\", \"path\": \"/names\", \"value\": [\"joe\", \"bob\"] } ]";
        Thing thing = new Thing();
        String actualThingJson = classUnderTest.getPatched(jsonPatch, thing);

        Thing expectedThing = new Thing();
        expectedThing.getNames().add("joe");
        expectedThing.getNames().add("bob");
        String expectedThingJson = mapper.writeValueAsString(expectedThing);

        Assert.assertEquals("Thing names should be joe and bob", expectedThingJson, actualThingJson);

    }

}
